name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install miri
      run: rustup toolchain install nightly && rustup +nightly component add miri
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests with miri
      run: cargo +nightly miri test
